spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri : ${patientservice.url}
          predicates :
            - Path= /patient/**
          filters:
            - AuthenticationFilter

        - id : r2
          uri : ${patientnoteservice.url}
          predicates :
            - Path= /service_note/**
          filters:
            - AuthenticationFilter

        - id: r3
          uri: ${patientassessmentservice.url}
          predicates :
            - Path= /assessment/**
          filters:
            - AuthenticationFilter

        - id : r4
          uri : ${patientservice.url}
          predicates :
            - Path= /api/auth/**

application:
  name: medilabo_gateway
medilabo:
  app:
    jwtCookieName: medilabo
    jwtSecret: mmmmmmmmmmmmmmmmmmmmmmmmmmmedilabo=Springggggggggggggggggggggggg
    jwtExpirationMs: 86400000

management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8888