spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri : http://localhost:8081
          predicates :
            - Path= /patient/**
        - id : r2
          uri : http://localhost:8082
          predicates :
            - Path= /service_note/**
        - id: r3
          uri: http://localhost:8083
          predicates :
            - Path= /assessment/**
        - id : r4
          uri : http://localhost:8081
          predicates :
            - Path= /api/auth/*            -
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8888